### ISSUE TITLE
Crash when auto property exists within subclass

### ISSUE THREAD

**Issue by oliwennell** [ComparetheMarket/fettle#38]
If this sublcass:
```
public class Thingy
{
      public bool IsThing => true;
 }
```

...is added to the `PartiallyTestedNumberComparison` class in the examples, then when coverage analysis is performed a crash occurs within Roslyn:

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode, SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root, SyntaxNode declaration, SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root, SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at Microsoft.CodeAnalysis.Editing.DocumentEditor.GetChangedDocument()
   at Fettle.Core.Internal.Instrumentation.<InstrumentDocument>d__1.MoveNext() in C:\dev\fettle\src\Core\Internal\Instrumentation.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Fettle.Core.CoverageAnalyser.<InstrumentThenCompileProject>d__7.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fettle.Core.CoverageAnalyser.<InstrumentThenCompileMultipleProjects>d__6.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fettle.Core.CoverageAnalyser.<AnalyseCoverage>d__5.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Fettle.Console.Program.AnalyseCoverage(ICoverageAnalyser coverageAnalyser, IOutputWriter outputWriter, Config config) in C:\dev\fettle\src\Console\Program.cs:line 123
   at Fettle.Console.Program.InternalEntryPoint(String[] args, Func`3 mutationTestRunnerFactory, Func`2 coverageAnalyserFactory, IOutputWriter outputWriter) in C:\dev\fettle\src\Console\Program.cs:line 71
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode, SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root, SyntaxNode declaration, SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root, SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at Microsoft.CodeAnalysis.Editing.DocumentEditor.GetChangedDocument()
   at Fettle.Core.Internal.Instrumentation.<InstrumentDocument>d__1.MoveNext() in C:\dev\fettle\src\Core\Internal\Instrumentation.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Fettle.Core.CoverageAnalyser.<InstrumentThenCompileProject>d__7.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fettle.Core.CoverageAnalyser.<InstrumentThenCompileMultipleProjects>d__6.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Fettle.Core.CoverageAnalyser.<AnalyseCoverage>d__5.MoveNext() in C:\dev\fettle\src\Core\CoverageAnalyser.cs:line 48<---
```

**Comment by oliwennell** [comment]
Related instrumentation code: `Instrumentation.InstrumentExpressionBodiedProperty`

Note that this method seemed to add an extra `;` on the end of the instrumented property, which may be related?
