### ISSUE TITLE
Crash on running with fettle.config.example.yml

### ISSUE THREAD

**Issue by shiyuw3** [ComparetheMarket/fettle#66]
I have built successfully from the source code (also HasSurvivingMutants project), but when I tried running  .\src\Console\bin\Debug\Fettle.Console.exe -c .\fettle.config.example.yml it doesn't work. The error messages are shown below. Anyone has ideas? Thanks ahead! 

An error ocurred that Fettle didn't expect.
System.AggregateException: One or more errors occurred. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create(IDictionary`2 properties)
   at Fettle.Core.MSBuildWorkspaceFactory.Create() in fettle\src\Core\Internal\MSBuildWorkspaceFactory.cs:line 16
   at Fettle.Core.Config.<FindMutatableDocuments>d__33.MoveNext() in fettle\src\Core\Config.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Fettle.Core.Config.<HasAnyMutatableDocuments>d__34.MoveNext() in fettle\src\Core\Config.cs:line 73
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Fettle.Console.Program.Run(String[] args, ITestRunnerFactory testRunnerFactory, Func`4 mutationTestRunnerFactory, Func`2 coverageAnalyserFactory, ISourceControlIntegration sourceControlIntegration, IOutputWriter outputWriter) in fettle\src\Console\Program.cs:line 100
---> (Inner Exception #0) System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create(IDictionary`2 properties)
   at Fettle.Core.MSBuildWorkspaceFactory.Create() in fettle\src\Core\Internal\MSBuildWorkspaceFactory.cs:line 16
   at Fettle.Core.Config.<FindMutatableDocuments>d__33.MoveNext() in fettle\src\Core\Config.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Fettle.Core.Config.<HasAnyMutatableDocuments>d__34.MoveNext() in fettle\src\Core\Config.cs:line 73<---

**Comment by shiyuw3** [comment]
nvm, the problem is from the wrong version of code analysis related .dll

**Comment by oliwennell** [comment]
Hi @shiyuw3 I'm a bit confused, how was the wrong version used? Is this an issue with Fettle itself?

**Comment by shiyuw3** [comment]
@oliwennell No its not an issue with fettle itself. I just used CodeAnalysis 2.0.0 from NuGet, everything works fine after I used the .dlls from tools folder of fettle (on NuGet). Thank you very much!
